#!/usr/bin/env python
# This is not the script you are looking for. This is just a wrapper.
# The actual scripts of this application were installed
# in subdirectories of /usr/lib/python-exec.
# You are most likely looking for one of those.

from __future__ import with_statement

# prepare a clean globals for exec()
new_globals = dict(globals())
# we have to keep the import top, so delete it from globals
del new_globals['with_statement']

import errno, os, os.path, sys

try:
	from epython import EPYTHON
except ImportError:
	EPYTHON = os.path.basename(sys.executable)
LEN_ARG=len(sys.argv)
ARGUM=sys.argv
if LEN_ARG >= 2:
	ARGS=" "+ARGUM[1]
if LEN_ARG >= 3:
	for num in range(2 ,LEN_ARG):
		ARGS=ARGS+" "+ARGUM[num]
if LEN_ARG >= 2:
	os.system('/usr/lib/python-exec/${EPYTHON}/sip'+ARGS)
else:
	os.system('/usr/lib/python-exec/${EPYTHON}/sip')
